### ISSUE TITLE
How long will it take to publish the code?

### ISSUE THREAD

**Issue by ZiyeHu** [ZhangGongjie/Meta-DETR#1]

**Comment by ZhangGongjie** [comment]
@ZiyeHu  Sorry for the waiting. Codes are already ready for open-source. However, our work is currently under review for a peer-reviewed conference or journal. Please understand that we wish to publish our codes only after proper recognition is given from academia. 

Thank you for your attention to our work. We will publish the codes as soon as possible.

**Comment by lander1003** [comment]
excuse me , how long will you publish the code , I'm expected to see the good code , thank you!

**Comment by ZhangGongjie** [comment]
@lander1003   If everything goes smoothly, June to July. But I cannot guarantee. Please understand we have strict protocols for code release as this research is partially funded by corporate funding. We will release ASAP. Thank you for your interest in our work. 
 : )

**Comment by Nastaszja** [comment]
Hello! Thank you, It is a very nice paper. I am highly interested in discovering the code release. Did you get any updates from your reviews (conference/journal)? Thank you in advance!

**Comment by ZhangGongjie** [comment]
Regret to let you know we are still revising this work. We have got much higher performance in our current improved version of Meta-DETR. Please stay tuned!

**Comment by vombategeht** [comment]
> Regret to let you know we are still revising this work. We have got much higher performance in our current improved version of Meta-DETR. Please stay tuned!

Can you give me a rough idea of when it'll be able to see the code? Sorry for rushing you. Just really interested in this work!
