### ISSUE TITLE
Is it possible to specify the prerequisites ?

### ISSUE THREAD

**Issue by Nastaszja** [ZhangGongjie/Meta-DETR#11]
Thanks for the work,

Is it possible to specify the prerequisites : python, cuda and pytorch version?

**Comment by ZhangGongjie** [comment]
Thanks for your interest.

Ubuntu 18.04 LTS Python 3.7 Pytorch 1.7.1 Cuda 10.2

**Comment by Nastaszja** [comment]
Thank you very much !

Also, is it possible to send some basic instructions on how to install and how to use your code?

**Comment by ZhangGongjie** [comment]
we are rushing an important deadline. We will release the cleaned-up codes, pre-trained models, logs, and detailed instruction in early Dec 2021.

**Comment by OlegJakushkin** [comment]
@ZhangGongjie Could you please share the pre-trained models (at least coco one for faster fine-tuning)?

**Comment by mburges-cvl** [comment]
> we are rushing an important deadline. We will release the cleaned-up codes, pre-trained models, logs, and detailed instruction in early Dec 2021.

Any updates? Currently trying to install it, installation instructions would be nice.

**Comment by ZhangGongjie** [comment]
Please see the updated README.md. Feel free to add new comments if you encounter any issues. Thank you
