### ISSUE TITLE
能快一点发布吗

### ISSUE THREAD

**Issue by LiuXinyu12378** [ZhangGongjie/Meta-DETR#2]

**Comment by ZhangGongjie** [comment]
@LiuXinyu12378 代码发布后，我会在此留言通知你。多谢关注！ : )

**Comment by LiuXinyu12378** [comment]
好的，但是这个代码的实用性是不是比较差，模型太大了，实时性怎么解决？

**Comment by ZhangGongjie** [comment]
模型的大小其实和一般的DETR frameworks差不多大。训练一般需要8-16块GPU，inference可在一块GPU上完成。请参考[文章](https://arxiv.org/abs/2103.11731v2) 的 Section 3.2.4, Section 6.5 和 Table 7。谢谢关注！ 
：）

**Comment by ZhangGongjie** [comment]
您好。我有注意到您主要从事嵌入式开发。我本科时候也是做这个的！ 如果您想在嵌入式设备（如 Raspberry Pi，单片机）上参考这个工作，目前可能确实无法解决模型参数量过大和实时性无法保证的问题。

**Comment by LiuXinyu12378** [comment]
是的，我本科在实验室做单片机和嵌入式和PID算法，现在工作主要是在做nlp和CV，现在在做的是few-shot object detection，在Few-shot-Object-Detection-via-Feature-Reweighting基础上做改进，但是效果提升并不明显，您有好的改进建议吗？考虑到实时性的问题，可能transformer改进的目标检测运行速度会比较慢，如果可以的话，我想加您的微信交流

**Comment by ZhangGongjie** [comment]
建议参考 https://github.com/ucbdrive/few-shot-object-detection， https://github.com/jiaxi-wu/MPSR，和 https://github.com/YoungXIAO13/FewShotDetection，都是基于 Faster R-CNN 的非常优秀的工作！

**Comment by ZhangGongjie** [comment]
建议参考 https://github.com/ucbdrive/few-shot-object-detection ， https://github.com/jiaxi-wu/MPSR ，和 https://github.com/YoungXIAO13/FewShotDetection ，都是基于 Faster R-CNN 的非常优秀的工作！

**Comment by LiuXinyu12378** [comment]
very感谢

**Comment by ZhangGongjie** [comment]
代码已开源 @LiuXinyu12378
