### ISSUE TITLE
Multi-scale version

### ISSUE THREAD

**Issue by Nastaszja** [ZhangGongjie/Meta-DETR#24]
Hello,

Did you implement your model in multi-scale versions ? If yes, is it possible to release the associated code?

Thank you

**Comment by ZhangGongjie** [comment]
Thank you for being so interested!

This is the implementation code for https://arxiv.org/abs/2103.11731v3, which has a significant difference with https://arxiv.org/abs/2103.11731v1.

The latest version of Meta-DETR does not have a multi-scale version. Thank you.
