### ISSUE TITLE
does anyone meet the same problem with me?

### ISSUE THREAD

**Issue by beeper00** [ZhangGongjie/Meta-DETR#27]
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

In the file named ms_deform_attn_func.py , line 18，i can't import MultiScaleDeformableAttention. Maybe i haven't this file . could anyone tell me why? Thank you.

**Comment by ZhangGongjie** [comment]
Thank you for your interest in our work! @beeper00  

Since Meta-DETR is developed based on Deformable DETR, we need to compile Deformable Attention Modules. So please run the following commands before running the codes.


```
# compile CUDA operators of Deformable Attention

cd Meta-DETR
cd ./models/ops
sh ./make.sh
python test.py  # unit test (should see all checking is True)

```

**Comment by beeper00** [comment]
Thank you! My training has begun




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangGongjie/Meta-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhangGongjie/Meta-DETR] does anyone meet the same problem with me? (Issue #27)





 
Thank you for your interest in our work! @beeper00
 
Since Meta-DETR is developed based on Deformable DETR, we need to compile Deformable Attention Modules. So please run the following commands before running the codes.
 # compile CUDA operators of Deformable Attention cd Meta-DETR cd ./models/ops sh ./make.sh python test.py  # unit test (should see all checking is True)

**Comment by ZhangGongjie** [comment]
So good to hear this! :)

**Comment by WenmuZhou** [comment]
> Thank you for your interest in our work! @beeper00
> 
> Since Meta-DETR is developed based on Deformable DETR, we need to compile Deformable Attention Modules. So please run the following commands before running the codes.
> 
> ```
> # compile CUDA operators of Deformable Attention
> 
> cd Meta-DETR
> cd ./models/ops
> sh ./make.sh
> python test.py  # unit test (should see all checking is True)
> ```

After I run this, there is still an error No module named 'MultiScaleDeformableAttention'
