### ISSUE TITLE
Release of the code?

### ISSUE THREAD

**Issue by gabrielhuang** [ZhangGongjie/Meta-DETR#3]
Hey there! Will you release the code soon? Thanks!

**Comment by ZhangGongjie** [comment]
Please stay tuned, thanks! Codes will be released ASAP.

**Comment by vadimkantorov** [comment]
Also waiting, we would use it for some more fair comparisons...

**Comment by ZhangGongjie** [comment]
Code released. Thanks! @vadimkantorov  @gabrielhuang
