### ISSUE TITLE
bAP of coco base-training

### ISSUE THREAD

**Issue by wwwbq** [ZhangGongjie/Meta-DETR#33]
请问在coco上base training阶段bAP能达到多少，论文中好像没有给出相关结果

**Comment by ZhangGongjie** [comment]
bAP for coco after the base-training stage is:

"test_coco_eval_bbox": [0.36701259733063385, 0.5694457555859925, 0.39037918007077743, 0.1903184458238878, 0.4232296969248381, 0.546235174017467, 0.32426961254305486, 0.5153352464259005, 0.5559305985164046, 0.31248911137889945, 0.633652820565051, 0.8008066330221726]

Thank you!
