### ISSUE TITLE
The implementation of instance segmentation.

### ISSUE THREAD

**Issue by hq-deng** [ZhangGongjie/Meta-DETR#47]
Could you please provide the code and checkpoints of few-shot instance segmentation? Thanks.

**Comment by ZhangGongjie** [comment]
Thanks for your interest. The codes I wrote for few-shot instance segmentation is a mess and are only used for a simple experiment.... Thus I do not have plans to release them.

**Comment by hq-deng** [comment]
Could your please send me a script for reference? No need to organize and verify. My email is "hanqiu1@ualberta.ca". Thanks.

**Comment by ZhangGongjie** [comment]
Done.

**Comment by nanfangAlan** [comment]
@ZhangGongjie Could you please send me the instance segmentation code also? My email is "nanfangalan@gmail.com". Thanks

**Comment by ZhangGongjie** [comment]
@nanfangAlan    I have left Nanyang Technological University and thus I no longer have access to the codes. So sorry about that.

You may try to contact hanqiu1@ualberta.ca for the `messy' codes.

Besides, the implementation is actually very simple. It is the exact implementation as the original DETR, except that we designed the pipeline as a meta-learning setup. When the few-shot finetuning is done, we freeze all object-detection-related parameters and the backbone parameters and train an additional instance segmentation head. 

Hope the above clarifies. Feel free to contact me for more details.

**Comment by nanfangAlan** [comment]
@ZhangGongjie Thanks for your reply. I'm checking the seg code in the original DETR. There are two more questions: 1. Which random seed sample can get the highest score and the "Results over a single run" score in your paper? 2. Did the other methods of "Results averaged over multiple random runs" take the same 10 random support sets as yours?
