### ISSUE TITLE
麻烦作者尽快发布源码

### ISSUE THREAD

**Issue by lehaifeng000** [ZhangGongjie/Meta-DETR#5]
读论文的时候感觉作者把FSDV和detr结合的思路还挺好的，但是一些创新点貌似都是detr里的，比如

> This paper presents a novel meta-detector framework, namely Meta-DETR, which eliminates region-wise prediction and instead meta-learns ob- ject localization and classification at image level in a unified and complementary manner.  

想看下复现的实验效果，麻烦作者尽快整理呀(抱拳)

**Comment by ZhangGongjie** [comment]
谢谢批评指教，我们改进了上一个版本的工作，论文已发布在https://arxiv.org/abs/2103.11731v3，代码将于10月开源。感谢关注！
