### ISSUE TITLE
Why top-100 in PostProcess?

### ISSUE THREAD

**Issue by nanfangAlan** [ZhangGongjie/Meta-DETR#59]
https://github.com/ZhangGongjie/Meta-DETR/blob/5879617d23e37cbf1dfcd6837da81a527e153985/models/meta_detr.py#L608
I noticed that you didn't simple softmax in PostProcess as the original DETR. Instead, you selected the top-K of all the pred boxes classes score, which I think is a multi-classification method, could you tell me why?

**Comment by ZhangGongjie** [comment]
This follows Deformable-DETR, which uses sigmoid to replace softmax for the classification task.
