### ISSUE TITLE
Regarding Background Encoding and Prototype

### ISSUE THREAD

**Issue by michaelku1** [ZhangGongjie/Meta-DETR#63]
Hi, Thanks for your work. I could not seem to find where background prototype was in the code. I was wondering how you compute it as mentioned in the paper? Many Thanks!

**Comment by ZhangGongjie** [comment]
Thanks for your interest in our work!
 
In models/attention.py  Line #44-45, we define the background prototype (learnable parameters) and task encodings for the background (fixed at zeros).

**Comment by michaelku1** [comment]
Thanks for your reply. I could see that you were trying to compute prototypes (as indicated as category codes in the code), but I believe these were computed from the gt boxes explicitly, whereas for the background class they should have been computed separately, so I was wondering what roi features you used to compute background prototypes? Thanks!

**Comment by michaelku1** [comment]
Thank you!
