### ISSUE TITLE
Performance of Meta-DETR without meta-finetuning?

### ISSUE THREAD

**Issue by stweigand97** [ZhangGongjie/Meta-DETR#75]
Some works on meta-learning for few-shot object detection also report their scores without meta-finetuning on the novel classes. Have you tried using Meta-DETR in this way? If so, what were the results & observations?

**Comment by nanfangAlan** [comment]
I've evaluated the provided model after base training on novel sets. It seems are overfitting on base sets.

COCO:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.004
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.008
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.040
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.085
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.093
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.051
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.085
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.166

VOC1:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.088
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.188
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.216
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.161
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.259

**Comment by ZhangGongjie** [comment]
Yes. Meta-DETR requires fine-tuning to work on novel classes.

**Comment by nanfangAlan** [comment]
Which reason do you think may limit the Meta-DETR to work on novel sets w/o fine-tuning, and how to solve this? As a class agnostic predictor, I thought Meta-DETR would get better results w/o fine-tuning.

> Yes. Meta-DETR requires fine-tuning to work on novel classes.

**Comment by stweigand97** [comment]
@nanfangAlan I think this is a phenomenon that can be observed for most meta learners. On the upside, there are some works that target this settings specifically.  Maybe [FS-DETR](https://arxiv.org/abs/2210.04845) could be an interesting paper to look at for you 😊

**Comment by nanfangAlan** [comment]
@stwerner97 Thanks for your reply. I've notice the FS-DETR, but it's improvement of results seems mainly because the use of pretrained UP-DETR, which can be found in Tab 4 of their paper, it cannot get comparable results without pretraining. I think it's a little unfair, cause other FSODs do not load UP-DETR params. Do you have any idea or know about other works which solve this problem? Thanks again.

**Comment by stweigand97** [comment]
@nanfangAlan I agree that most of the improvements are due to the pre-training stage and would also apply to related works in some capacity. 

I still think that its a very worthwhile read, since there are too few meta-learning works reporting their performance without fine-tuning and pre-training is a valid method to improve overall performance. I also don't see what other components to change to close the fine-tuning vs. non-fine-tuning gap, since improving the architectural design most likely will benefit fine-tuning performance as well.

Unfortunately, I am not and would also be highly interested in such works. Of course there are a lot of works on zero-shot detection using vision-language models, but that's not what I am looking for. 😊

**Comment by stweigand97** [comment]
Ah, I just remembered *AirDet: Few-Shot Detection without Fine-Tuning for Autonomous Exploration*, which also claims being a few-shot object detector without fine-tuning. 😊
