### ISSUE TITLE
在训练自己的数据集时，类别数报错。

### ISSUE THREAD

**Issue by qjh666888** [ZhangGongjie/Meta-DETR#78]
Traceback (most recent call last):
  File "main.py", line 371, in <module>
    main(args)
  File "main.py", line 254, in main
    missing_keys, unexpected_keys = model_without_ddp.load_state_dict(checkpoint['model'], strict=False)
  File "/data/qjh/envs/meta-detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MetaDETR:
        size mismatch for category_codes_cls.L.weight_g: copying a param with shape torch.Size([91, 1]) from checkpoint, the shape in current model is torch.Size([10, 1]).
        size mismatch for category_codes_cls.L.weight_v: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([10, 256]).

有人遇到过吗，应该怎么修改

**Comment by NHeLv1** [comment]
您好，想和您讨论一下训练自己数据集的问题，只需要按照coco格式存放就可以了吗

**Comment by qjh666888** [comment]
我没有使用这个代码训练自己的数据集



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shen ***@***.***&gt;; 
发送时间: 2024年2月28日(星期三) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ZhangGongjie/Meta-DETR] 在训练自己的数据集时，类别数报错。 (Issue #78)





 
您好，想和您讨论一下训练自己数据集的问题，只需要按照coco格式存放就可以了吗
