### ISSUE TITLE
Fine-tuning time

### ISSUE THREAD

**Issue by kaeline** [ZhangGongjie/Meta-DETR#82]
Hello! Thank you for publishing the code!
I am curious about the expected performance of the second fine-tuning step. 
I run it on 2 14GB GPU with latest CUDA and it is extremely slow (approx. 5 min per epoch x 500 epoch = 2500 minutes ~=40 hr).
Is this expected performance? Or does it mean something is working incorrectly?
I am using the provided COCO dataset with the default fine-tuning script.

**Comment by ZhangGongjie** [comment]
Yeah. Using 8 GPUs would make the running time faster. That's the issue with meta-learning: it trains slower and training needs more computation.
